# Generated by Django 5.2.8 on 2025-12-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_phone_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points_balance",
            field=models.IntegerField(default=0),
        ),
    ]
