# Generated by Django 5.2.8 on 2025-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "size")},
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional override. Leave empty to use product base_price.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="color",
        ),
    ]
