# Generated by Django 5.2.8 on 2026-01-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_shop_now",
            field=models.BooleanField(default=False),
        ),
    ]
