# Generated by Django 5.2.8 on 2026-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_shop_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Upload a .glb 3D model file for this product",
                null=True,
                upload_to="models/3d/",
            ),
        ),
    ]
