# Generated by Django 5.2.8 on 2026-03-14 17:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_model_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Upload a .glb 3D model file for this product",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location="/Users/hey/threads_and_trends/backend/media",
                ),
                upload_to="models/3d/",
            ),
        ),
    ]
