# Generated by Django 5.2.8 on 2026-04-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_image',
            field=models.ImageField(blank=True, help_text='Side-profile transparent PNG for AR try-on (works best with transparent background)', null=True, upload_to='products/ar/'),
        ),
    ]
