# Generated by Django 5.2.8 on 2025-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("esewa", "eSewa")],
                default="cod",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="points_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="points_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="points_redeemed",
            field=models.IntegerField(default=0),
        ),
    ]
