# Generated by Django 5.2.8 on 2026-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status_ordertimelineevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="esewa_transaction_uuid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
