# Generated by Django 5.2.8 on 2026-02-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_esewa_transaction_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_ids",
                    models.JSONField(
                        default=list, help_text="List of OrderItem IDs being returned"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_size", "Wrong Size"),
                            ("defective", "Defective Product"),
                            ("damaged", "Product Damaged in Transit"),
                            ("wrong_item", "Wrong Item Received"),
                            ("changed_mind", "Changed Mind"),
                            ("quality_issues", "Product Quality Issues"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional details about the return",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("label_sent", "Return Label Sent"),
                            ("received", "Items Received"),
                            ("refunded", "Refunded"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shipping_fee_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "return_tracking_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="return_requests/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="orders.returnrequest",
                    ),
                ),
            ],
        ),
    ]
